angularVersion: 1.2.17
version: 1
baseurl: '/developers-stage'
exclude: [README.md, Gemfile, Gemfile.lock, CNAME]
apiDomain: "https://stage-api.zenginehq.com"
clientDomain: "https://stage-platform.zenginehq.com"
authDomain: "https://stage-auth.zenginehq.com"
supportDomain: "http://support.zenginehq.com"
developerDomain: "https://github.com/ZengineHQ/developers-stage"
angularDomain: "https://code.angularjs.org"
communityUrl: "https://groups.google.com/forum/#!forum/zengine-development/"
demoClientId: "rest-api-quick-start-demo"
rootDomain: zenginehq.com
apiKey: false
kramdown:
  input: GFM # enable github flavored markdown
productName: Zengine
logo: <span class="logo">Zengine</span> Developers</span>
